# Generated by Django 5.0.1 on 2024-01-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_answers_user_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sessions',
        ),
    ]
