# Generated by Django 5.0.1 on 2024-01-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportmessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportmessage',
            old_name='status',
            new_name='active',
        ),
    ]
