# Generated by Django 5.0.1 on 2024-01-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coaching_session',
            old_name='user',
            new_name='owner',
        ),
    ]
