# Generated by Django 5.0.1 on 2024-01-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_sessions', '0005_alter_coaching_session_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaching_session',
            name='scheduled_datetime',
        ),
        migrations.AddField(
            model_name='coaching_session',
            name='scheduled_date',
            field=models.DateField(default='2013-06-26'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coaching_session',
            name='scheduled_time',
            field=models.TimeField(default='20:00'),
        ),
    ]
