# Generated by Django 5.0.1 on 2024-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_sessions', '0006_remove_coaching_session_scheduled_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching_session',
            name='scheduled_time',
            field=models.TimeField(),
        ),
    ]
