# Generated by Django 5.0.1 on 2024-01-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_sessions', '0010_alter_coaching_session_coach_and_more'),
        ('session_types', '0003_session_type_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching_session',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coaching_sessions', to='session_types.session_type'),
        ),
    ]
