# Generated by Django 5.0.1 on 2024-01-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='question1answer',
            field=models.CharField(choices=[('a', 'option a'), ('b', 'option b'), ('c', 'option c'), ('d', 'option d'), ('e', 'option e')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question2answer',
            field=models.CharField(choices=[('a', 'option a'), ('b', 'option b'), ('c', 'option c'), ('d', 'option d'), ('e', 'option e')], default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question3answer',
            field=models.CharField(choices=[('a', 'option a'), ('b', 'option b'), ('c', 'option c'), ('d', 'option d'), ('e', 'option e')], default='b', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question4answer',
            field=models.CharField(choices=[('a', 'option a'), ('b', 'option b'), ('c', 'option c'), ('d', 'option d'), ('e', 'option e')], default='b', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question5answer',
            field=models.CharField(choices=[('a', 'option a'), ('b', 'option b'), ('c', 'option c'), ('d', 'option d'), ('e', 'option e')], default='c', max_length=1),
            preserve_default=False,
        ),
    ]
