# Generated by Django 5.0.1 on 2024-01-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='brief',
            field=models.CharField(blank=True, default='Coach brief.', max_length=1000, null=True),
        ),
    ]
