# Generated by Django 5.0.1 on 2024-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coach_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', null=True),
        ),
    ]
