# Generated by Django 5.0.1 on 2024-01-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_Types',
            new_name='Session_Type',
        ),
    ]
