# Generated by Django 5.0.1 on 2024-01-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_types', '0002_rename_session_types_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_type',
            name='brief',
            field=models.CharField(default='Pocket full of sunshine', max_length=255),
        ),
    ]
